pipeline {
    agent any

    // ---------------------------------------------------------
    // TRIGGERS: nightly schedule + PR-merge webhook + manual
    // (manual trigger needs no config — the "Build Now" button
    // in Jenkins always works)
    // ---------------------------------------------------------
    triggers {
        // Nightly build at 2:00 AM server time
        cron('0 2 * * *')

        // Fires when GitHub sends a webhook (e.g. on PR merge to main).
        // Requires the GitHub plugin + a webhook configured in your
        // GitHub repo settings pointing to:
        // http://<jenkins-url>/github-webhook/
        githubPush()
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
    }

    environment {
        // Adjust these paths/URLs to match your project
        NODE_VERSION   = '18'
        POSTMAN_COLLECTION = 'postman/collection.json'
        POSTMAN_ENV         = 'postman/environment.json'
    }

    stages {

        // 1. Checkout code
        stage('Checkout code') {
            steps {
                checkout scm
            }
        }

        // 2. Install dependencies
        stage('Install dependencies') {
            steps {
                bat '''
                    node -v
                    npm install
                    npm install -g newman newman-reporter-htmlextra
                '''
            }
        }

        // 3. Run Selenium suite (headless, parallel where possible)
        stage('Run Selenium suite') {
            steps {
                bat '''
                    REM Example for a Maven/TestNG Selenium project running headless & in parallel.
                    REM Adjust to your actual test runner (pytest, Mocha, TestNG, JUnit, etc.)
                    mvn -B -Dheadless=true -DthreadCount=4 -Dparallel=methods test
                '''
            }
            post {
                always {
                    junit testResults: '**/target/surefire-reports/*.xml', allowEmptyResults: true
                }
            }
        }

        // 4. Run Postman suite via Newman
        stage('Run Postman suite (Newman)') {
            steps {
                bat '''
                    newman run "%POSTMAN_COLLECTION%" ^
                        -e "%POSTMAN_ENV%" ^
                        --reporters cli,junit,htmlextra ^
                        --reporter-junit-export newman/report.xml ^
                        --reporter-htmlextra-export newman/report.html
                '''
            }
        }

        // 5. Publish test reports (JUnit / HTML / Allure)
        stage('Publish test reports') {
            steps {
                // JUnit (Selenium + Postman results combined)
                junit testResults: '**/target/surefire-reports/*.xml, newman/report.xml', allowEmptyResults: true

                // HTML report (Newman htmlextra output)
                publishHTML(target: [
                    reportName: 'Postman HTML Report',
                    reportDir: 'newman',
                    reportFiles: 'report.html',
                    keepAll: true,
                    alwaysLinkToLastBuild: true,
                    allowMissing: true
                ])

                // Allure (requires allure-results generated by your Selenium framework)
                allure includeProperties: false, results: [[path: 'allure-results']]
            }
        }
    }

    // 6. Mark build pass/fail
    post {
        success {
            echo '✅ Build PASSED — all tests succeeded.'
        }
        failure {
            echo '❌ Build FAILED — check JUnit/HTML/Allure reports for details.'
        }
        unstable {
            echo '⚠️ Build UNSTABLE — some tests failed but pipeline completed.'
        }
        always {
            cleanWs()
        }
    }
}
